set -g base-index 1
set -g pane-base-index 1

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

bind | split-window -h -f

bind r source-file ~/.tmux.conf

set -g mouse on

# panes
set -g pane-border-style 'fg=black'
set -g pane-active-border-style 'fg=black'

# statusbar
set -g status-position top
set -g status-style 'fg=black'
set -g status-justify left

set -g status-right ''

setw -g window-status-current-style 'fg=white bg=purple'
setw -g window-status-current-format ' <#I> #W #F '

setw -g window-status-style 'fg=gray bg=black'
setw -g window-status-format ' <#I> #W #F '
